#!/bin/bash
while true
do
    if ! /usr/bin/diff -q "/Kilgorezer/endpointurls.json" "/LF/Bulk/endpointurls.json" > /dev/null
    then
        /bin/cp "/Kilgorezer/endpointurls.json" "/LF/Bulk/endpointurls.json"
    fi
    /bin/sleep 5
done

